version: "3"
services:
    web:
        build: .
        ports:
            - 5000:5000
        volumes:
            - /userCode/:/code
        links:
            - database:backendDb
    database:
        image: mysql/mysql-server:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=testUser
            - MYSQL_PASSWORD=admin123
            - MYSQL_DATABASE=backend
        volumes:
            - /userCode/db/init.sql:/docker-entrypoint-initDb.d/init.sql
